### PR TITLE
Update major and minor dependencies.

### PR DESCRIPTION
**Pull request by dhirajshettymoj**
Major updates - 
cookie-session                                 1.4.0 to 2.0.0
dotenv						10.0.0 to 16.0.2
helmet						4.8.0 to 6.0.0
http-errors					1.8.0 to 2.0.0
superagent					7.1.6 to 8.0.0
@types/jest					28.1.8 to 29.0.3
husky						7.0.2 to 8.0.1
jest							28.1.3 to 29.1.1
jest-environment-jsdom			28.1.3 to 29.1.1
jest-jasmine2					28.1.3 to 29.1.1
ts-jest						28.0.8 to 29.0.2

Minor updates - 
@typescript-eslint/eslint-plugin	5.37.0 to 5.38.1
@typescript-eslint/parser		5.37.0 to 5.38.1
@types/http-errors				1.8.1 to 1.8.2
typescript					4.8.3 to 4.8.4

### CODE REVIEW

**Comment by dhirajshettymoj** [comment]
The following dependencies are still showing as outdated. Updating them was throwing errors so will be looked at individually at a later point - 
Package                       Current    Wanted   Latest  Location                                  Depended by
@ministryofjustice/frontend     0.2.6     0.2.6    1.5.0  node_modules/@ministryofjustice/frontend  send-legal-mail-to-prisons
@types/node                  16.11.62  16.11.62  18.7.23  node_modules/@types/node                  send-legal-mail-to-prisons
@types/redis                   2.8.32    2.8.32   4.0.11  node_modules/@types/redis                 send-legal-mail-to-prisons
cypress                         8.7.0     8.7.0   10.9.0  node_modules/cypress                      send-legal-mail-to-prisons
cypress-axe                    0.13.0    0.13.0    1.0.0  node_modules/cypress-axe                  send-legal-mail-to-prisons
eslint                         7.32.0    7.32.0   8.24.0  node_modules/eslint                       send-legal-mail-to-prisons
eslint-config-airbnb-base      14.2.1    14.2.1   15.0.0  node_modules/eslint-config-airbnb-base    send-legal-mail-to-prisons
express-request-id              1.4.1     1.4.1    2.0.1  node_modules/express-request-id           send-legal-mail-to-prisons
redis                           3.1.2     3.1.2    4.3.1  node_modules/redis                        send-legal-mail-to-prisons

**Review by psoleckimoj — APPROVED** [review]
LGTM!

**Comment by psoleckimoj** [comment]
> The following dependencies are still showing as outdated. Updating them was throwing errors so will be looked at individually at a later point - Package Current Wanted Latest @ministryofjustice/frontend 0.2.6 0.2.6 1.5.0 @types/node 16.11.62 16.11.62 18.7.23 @types/redis 2.8.32 2.8.32 4.0.11 cypress 8.7.0 8.7.0 10.9.0 cypress-axe 0.13.0 0.13.0 1.0.0 eslint 7.32.0 7.32.0 8.24.0 eslint-config-airbnb-base 14.2.1 14.2.1 15.0.0 express-request-id 1.4.1 1.4.1 2.0.1 redis 3.1.2 3.1.2 4.3.1

Redis needs updatin as does Cypress, the node types will always show because were running node 16 and not 18. I pulled express-request-id into our code base and removed the module, worth looking at the PR I did, can always help with that. Front end will need looking at, might just update but would need regression checks to make sure it hasn't broken anything.

**Comment by dhirajshettymoj** [comment]
> > The following dependencies are still showing as outdated. Updating them was throwing errors so will be looked at individually at a later point - Package Current Wanted Latest @ministryofjustice/frontend 0.2.6 0.2.6 1.5.0 @types/node 16.11.62 16.11.62 18.7.23 @types/redis 2.8.32 2.8.32 4.0.11 cypress 8.7.0 8.7.0 10.9.0 cypress-axe 0.13.0 0.13.0 1.0.0 eslint 7.32.0 7.32.0 8.24.0 eslint-config-airbnb-base 14.2.1 14.2.1 15.0.0 express-request-id 1.4.1 1.4.1 2.0.1 redis 3.1.2 3.1.2 4.3.1
> 
> Redis needs updatin as does Cypress, the node types will always show because were running node 16 and not 18. I pulled express-request-id into our code base and removed the module, worth looking at the PR I did, can always help with that. Front end will need looking at, might just update but would need regression checks to make sure it hasn't broken anything.

Thanks. There's a story to update the front page. Once that is done I will have a relook at updating cypress, redis and the express-request-id update as mentioned.

**Review by tpmcgowan — APPROVED** [review]
LGTM

**Pull request merged**
